GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU1NDEzMzUwLCJleHAiOjE2NTU0MTMzNzV9.JGt-0npY6LePhD9I2tFPgHuc1g7PfX9kAPwQLAlDb34
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU1NDEzNjUxfQ.g7qvA1oQJz5vFPssj9BUW2yNnGzQwwXxbmausG0KVXg"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU1NDEzNjUxfQ.g7qvA1oQJz5vFPssj9BUW2yNnGzQwwXxbmausG0KVXg"
}